{
 "title": "MySQL MyISAM/Aria Metrics",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "MyISAM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MyISAM Indexes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_reads{instance=\"$host\"}[5m])",
     "legendFormat": "Key Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Key Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Write Requests"
    }
   ]
  },
  {
   "title": "MyISAM Key Buffer Performance",
   "type": "graph",
   "description": "The `Key Read Ratio`  (Key_reads/Key_read_requests) ratio should normally be less than 0.01.\n\nThe  `Key Write Ratio` (Key_writes/Key_write_requests) ratio is usually near 1 if you are using mostly updates and deletes, but might be much smaller if you tend to do updates that affect many rows at the same time or if you are using the `DELAY_KEY_WRITE` table option.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{instance=\"$host\"}[$interval]) / rate(mysql_global_status_key_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_reads{instance=\"$host\"}[5m]) / irate(mysql_global_status_key_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Read Ratio"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{instance=\"$host\"}[$interval]) / rate(mysql_global_status_key_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_writes{instance=\"$host\"}[5m]) / irate(mysql_global_status_key_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Key Write Ratio"
    }
   ]
  },
  {
   "title": "MyISAM Key Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"} - mysql_global_status_key_blocks_unused{instance=\"$host\"} * mysql_global_variables_key_cache_block_size{instance=\"$host\"}",
     "legendFormat": "Key Blocks Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_key_blocks_not_flushed{instance=\"$host\"} * mysql_global_variables_key_cache_block_size{instance=\"$host\"}",
     "legendFormat": "Key Blocks Not Flushed"
    }
   ]
  },
  { "title": "Aria Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Aria Pagecache Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aria_pagecache_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Aria Pagecache Write Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aria_pagecache_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "Aria Pagecache Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aria_pagecache_reads{instance=\"$host\"}[5m])",
     "legendFormat": "Aria Pagecache Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aria_pagecache_writes{instance=\"$host\"}[5m])",
     "legendFormat": "Aria Pagecache Writes"
    }
   ]
  },
  {
   "title": "Aria Storage Engine",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "content": "The Aria Storage Engine ships only with MariaDB so you should expect to see empty Aria graphs if you are running Percona Server for MySQL, MySQL Community, or MySQL Enterprise."
  },
  {
   "title": "Aria Transaction Log Syncs",
   "type": "graph",
   "description": "The number of Aria log fsyncs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_aria_transaction_log_syncs{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aria_transaction_log_syncs{instance=\"$host\"}[5m])",
     "legendFormat": "Aria Transaction Log Syncs"
    }
   ]
  },
  {
   "title": "Aria Pagecache Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_not_flushed{instance=\"$host\"}",
     "legendFormat": "Aria Pagecache Blocks Not Flushed"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_used{instance=\"$host\"}",
     "legendFormat": "Aria Pagecache Blocks Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_unused{instance=\"$host\"}",
     "legendFormat": "Aria Pagecache Blocks Unused"
    },
    {
     "expr": "mysql_global_variables_aria_pagecache_buffer_size{instance=\"$host\"} / mysql_global_variables_aria_block_size{instance=\"$host\"}",
     "legendFormat": "Aria Pagecache Total Blocks"
    }
   ]
  }
 ]
}