{
 "title": "MySQL Performance Schema Wait Event Analyses",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_global_variables_performance_schema, instance)"
   },
   {
    "name": "event",
    "label": "Event",
    "query": "label_values(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\"}, event_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "Count - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Load - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Avg Wait Time - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name=~\"$event\"}[$interval])/rate(mysql_perf_schema_events_waits_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])/irate(mysql_perf_schema_events_waits_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  }
 ]
}