{
 "title": "NUMA Overview",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_memory_numa_MemTotal, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_memory_numa_numa_hit_total,node)"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemTotal{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{instance=\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemUsed{instance=\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Free Memory Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{instance=\"$host\"}) * 100 /\nsum by (node) (node_memory_numa_MemTotal{instance=\"$host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "NUMA Memory Usage Types",
   "type": "graph",
   "description": "**Dirty** Memory waiting to be written back to disk\n\n**Bounce** Memory used for block device bounce buffers\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**KernelStack** The memory the kernel stack uses. This is not reclaimable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(node_memory_numa_Active{instance=\"$host\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(node_memory_numa_Inactive{instance=\"$host\"})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum(node_memory_numa_Dirty{instance=\"$host\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(node_memory_numa_Bounce{instance=\"$host\"})",
     "legendFormat": "Bounce"
    },
    {
     "expr": "sum(node_memory_numa_Mapped{instance=\"$host\"})",
     "legendFormat": "Mapped"
    },
    {
     "expr": "sum(node_memory_numa_KernelStack{instance=\"$host\"})",
     "legendFormat": "KernelStack"
    }
   ]
  },
  {
   "title": "NUMA Allocation Hits",
   "type": "graph",
   "description": "Memory successfully allocated on this node as intended.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_hit_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{instance=\"$host\"}[5m])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_hit_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_hit_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "NUMA Allocation Missed",
   "type": "graph",
   "description": "**Memory missed** is allocated on a node despite the process preferring some different node.\n\n**Memory foreign** is intended for a node, but actually allocated on some different node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m])",
     "legendFormat": "Missed Node $node"
    },
    {
     "expr": "rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m]) * 100 /\n(rate(node_memory_numa_numa_hit_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{instance=\"$host\"}[5m]) + \nrate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Missed ratio Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Total Missed"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m])) * 100 /\nsum((rate(node_memory_numa_numa_hit_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_hit_total{instance=\"$host\"}[5m])) + \nsum(rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m])))",
     "legendFormat": "Total Missed Ratio"
    }
   ]
  },
  {
   "title": "Anonymous Memory",
   "type": "graph",
   "description": "**Active anonymous memory** that has been used more recently and usually not swapped out.\n\n**Inactive anonymous memory** that has not been used recently and can be swapped out.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Active_anon{instance=\"$host\"}[$interval]))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_Inactive_anon{instance=\"$host\"}[$interval]))",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "NUMA File (PageCache)",
   "type": "graph",
   "description": "**Active(file)** Pagecache memory that has been used more recently and usually not reclaimed until needed\n\n**Inactive(file)** Pagecache memory that can be reclaimed without huge performance impact",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Active_file{instance=\"$host\"}[$interval]))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_Inactive_file{instance=\"$host\"}[$interval]))",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "graph",
   "description": "**Shmem** Total used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Shmem{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemHugePages{instance=\"$host\"})",
     "legendFormat": "HugePages"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemPmdMapped{instance=\"$host\"})",
     "legendFormat": "PmdMapped"
    }
   ]
  },
  {
   "title": "HugePages Statistic",
   "type": "graph",
   "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Total{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Free{instance=\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Surp{instance=\"$host\"})",
     "legendFormat": "Surplus"
    }
   ]
  },
  {
   "title": "Local Processes",
   "type": "graph",
   "description": "Memory allocated on a node while a process was running on it.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remote Processes",
   "type": "graph",
   "description": "Memory allocated on a node while a process was running on some other node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m])) * 100 /\n(sum(rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m])) + \nsum(rate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_local_node_total{instance=\"$host\"}[$interval])))",
     "legendFormat": "Total remote processes rate"
    }
   ]
  },
  {
   "title": "Slab Memory",
   "type": "graph",
   "description": "**Slab** allocation is a memory management mechanism intended for the efficient memory allocation of kernel objects.\n\n**SReclaimable** The part of the Slab that might be reclaimed (such as caches).\n\n**SUnreclaim** The part of the Slab that can't be reclaimed under memory pressure",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Slab{instance=\"$host\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_SReclaimable{instance=\"$host\"}[$interval]))",
     "legendFormat": "Reclaimable"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_SUnreclaim{instance=\"$host\"}[$interval]))",
     "legendFormat": "Unreclaim"
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Node $node - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_MemTotal{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Total"
      },
      {
       "expr": "avg_over_time(node_memory_numa_MemFree{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Free"
      },
      {
       "expr": "avg_over_time(node_memory_numa_MemUsed{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Node $node - Free Memory Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_memory_numa_MemFree{instance=\"$host\", node=\"$node\"}) * 100 /\n(node_memory_numa_MemTotal{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Memory Usage Types",
     "type": "graph",
     "description": "**Dirty** Memory waiting to be written back to disk\n\n**Bounce** Memory used for block device bounce buffers\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**KernelStack** The memory the kernel stack uses. This is not reclaimable.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg_over_time(node_memory_numa_Active{instance=\"$host\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive{instance=\"$host\"}[$interval])",
       "legendFormat": "Inactive"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Dirty{instance=\"$host\"}[$interval])",
       "legendFormat": "Dirty"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Bounce{instance=\"$host\"}[$interval])",
       "legendFormat": "Bounce"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Mapped{instance=\"$host\"}[$interval])",
       "legendFormat": "Mapped"
      },
      {
       "expr": "avg_over_time(node_memory_numa_KernelStack{instance=\"$host\"}[$interval])",
       "legendFormat": "KernelStack"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Allocation Hits",
     "type": "graph",
     "description": "Memory successfully allocated on this node as intended.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_numa_hit_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{instance=\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Hit Total"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Allocation Missed/Foreign",
     "type": "graph",
     "description": "**Memory missed** is allocated on a node despite the process preferring some different node.\n\n**Memory foreign** is intended for a node, but actually allocated on some different node.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Missed"
      },
      {
       "expr": "rate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[5m]) * 100 /\n(rate(node_memory_numa_numa_hit_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{instance=\"$host\", node=\"$node\"}[5m]) + \nrate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\", node=\"$node\"}[5m]))",
       "legendFormat": "Missed ratio"
      }
     ]
    },
    {
     "title": "Node $node - Anonymous Memory",
     "type": "graph",
     "description": "**Active** Anonymous memory that has been used more recently and usually not swapped out\n\n**Inactive** Anonymous memory that has not been used recently and can be swapped out",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Active_anon{instance=\"$host\",node=\"$node\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive_anon{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Node $node - NUMA File (PageCache)",
     "type": "graph",
     "description": "**Active(file)** Pagecache memory that has been used more recently and usually not reclaimed until needed\n\n**Inactive(file)** Pagecache memory that can be reclaimed without huge performance impact",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Active_file{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive_file{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Node $node - Shared Memory",
     "type": "graph",
     "description": "**Shmem** Total used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (node_memory_numa_Shmem{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (node_memory_numa_ShmemHugePages{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "HugePages"
      },
      {
       "expr": "sum by (node) (node_memory_numa_ShmemPmdMapped{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "PmdMapped"
      }
     ]
    },
    {
     "title": "Node $node - HugePages Statistic",
     "type": "graph",
     "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Total{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Free{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Surp{instance=\"$host\", node=\"$node\"})",
       "legendFormat": "Surplus"
      }
     ]
    },
    {
     "title": "Node $node - Local Processes",
     "type": "graph",
     "description": "Memory allocated on this node while a process was running on it.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_local_node_total{instance=\"$host\",node=\"$node\"}[$interval]) or\nirate(node_memory_numa_local_node_total{instance=\"$host\",node=\"$node\"}[$interval])",
       "legendFormat": "Node $node"
      }
     ]
    },
    {
     "title": "Node $node - Remote Processes",
     "type": "graph",
     "description": "Memory allocated on this node while a process was running on some other node.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Node $node"
      }
     ]
    },
    {
     "title": "Node $node - Slab Memory",
     "type": "graph",
     "description": "**Slab** allocation is a memory management mechanism intended for the efficient memory allocation of kernel objects.\n\n**SReclaimable** The part of the Slab that might be reclaimed (such as caches).\n\n**SUnreclaim** The part of the Slab that can't be reclaimed under memory pressure",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Slab{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Total"
      },
      {
       "expr": "avg_over_time(node_memory_numa_SReclaimable{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Reclaimable"
      },
      {
       "expr": "avg_over_time(node_memory_numa_SUnreclaim{instance=\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Unreclaim"
      }
     ]
    }
   ]
  }
 ]
}