{
 "title": "Prometheus Exporters Overview",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Exporters Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg CPU Usage per Host",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((sum(rate(process_cpu_seconds_total{job!=\"prometheus\",job!=\"grafana\",instance=~\"$host\"}[$interval])) by (instance) or sum(irate(process_cpu_seconds_total{job!=\"prometheus\",instance=~\"$host\"}[5m])) by (instance)) / count(node_cpu{mode=\"user\",instance=~\"$host\"}) by (instance)) by ()*100"
    }
   ]
  },
  {
   "title": "Avg Memory Usage per Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(sum(process_resident_memory_bytes{job!=\"prometheus\",job!=\"grafana\",instance=~\"$host\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Monitored Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(count(process_open_fds{job!=\"prometheus\",job!=\"grafana\",instance=~\"$host\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(process_open_fds{job!=\"prometheus\",job!=\"grafana\",instance=~\"$host\"}) "
    }
   ]
  },
  {
   "title": "Prometheus Exporters Resource Usage by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}[$interval])) by (instance) or sum(irate(process_cpu_seconds_total{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}[5m])) by (instance)) / count(node_cpu{mode=\"user\", instance=~\"$host\"}) by (instance) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus Resource usage by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "CPU Cores Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg(rate(process_cpu_seconds_total{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}[$interval])) by (job) or avg(irate(process_cpu_seconds_total{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}[5m])) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$host\",job!=\"prometheus\",job!=\"grafana\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "host" },
  { "title": "Host", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 }, "content": "$host" },
  {
   "title": "CPU  Used",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(rate(process_cpu_seconds_total{instance=\"$host\",job!=\"prometheus\",job!=\"grafana\"}[$interval])) by (instance) \nor sum(irate(process_cpu_seconds_total{instance=\"$host\",job!=\"prometheus\",job!=\"grafana\"}[5m])) by (instance)) \n/ count(node_cpu{instance=\"$host\",mode=\"user\"}) by (instance)*100) or \nsum by () ((max_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(process_resident_memory_bytes{instance=\"$host\",job!=\"prometheus\",job!=\"grafana\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(process_open_fds{instance=\"$host\",job!=\"prometheus\",job!=\"grafana\"}) "
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"user\", instance=\"$host\"}) or count(rdsosmetrics_General_numVCPUs)"
    }
   ]
  }
 ]
}