{
 "title": "Prometheus",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Prometheus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"pmm-server\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*sum(go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}) by () / \nsum(node_memory_MemTotal{instance=\"pmm-server\"}) by ()"
    }
   ]
  },
  {
   "title": "Scrapes Performed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Samples Ingested in the head block",
   "type": "singlestat",
   "description": "Number of appended samples",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[$interval]) or irate(prometheus_tsdb_head_samples_appended_total[5m])"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval]) or irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
       "legendFormat": "CPU Cores Used"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"pmm-server\"})",
       "legendFormat": "CPU Cores Total"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"pmm-server\"})*0.75",
       "legendFormat": "Recommended Limit"
      }
     ]
    },
    {
     "title": "Prometheus Process  Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}",
       "legendFormat": "Go Memory Allocated and In Use"
      },
      {
       "expr": "node_memory_MemTotal{instance=\"pmm-server\"}",
       "legendFormat": "Total System Memory"
      }
     ]
    },
    {
     "title": "Disk Space Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size{instance=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_size{instance=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ) - \n(node_filesystem_free{instance=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_free{instance=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})",
       "legendFormat": "Used Disk Space"
      },
      {
       "expr": "node_filesystem_free{instance=\"pmm-server\", mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_free{instance=\"pmm-server\", mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
       "legendFormat": "Free Disk Space"
      },
      {
       "expr": "node_filesystem_size{instance=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_size{instance=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
       "legendFormat": "Total Disk Space"
      }
     ]
    },
    {
     "title": "Time before run out of space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "h" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free{instance=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}/\nclamp_min((node_filesystem_free{instance=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} - \npredict_linear(node_filesystem_free{instance=\"pmm-server\", mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[1h], 1 * 3600)),0)\nor\nnode_filesystem_free{instance=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}/\nclamp_min((node_filesystem_free{instance=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} - \npredict_linear(node_filesystem_free{instance=\"pmm-server\", mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[1h], 1 * 3600)),0)",
       "legendFormat": "Time Left on {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage (TSDB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data blocks",
     "type": "singlestat",
     "description": "Number of currently loaded data blocks",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "prometheus_tsdb_blocks_loaded" }
     ]
    },
    {
     "title": "Total chunks in the head block",
     "type": "singlestat",
     "description": "Total number of chunks in the head block",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "prometheus_tsdb_head_chunks" }
     ]
    },
    {
     "title": "Number of series in the head block",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "series" }
     ]
    },
    {
     "title": "Current retention period of the head block",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "prometheus_tsdb_head_max_time - prometheus_tsdb_head_min_time"
      }
     ]
    },
    {
     "title": "Activity with chunks in the head block",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total[$interval]) or irate(prometheus_tsdb_head_chunks_created_total[5m])",
       "legendFormat": "created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total[$interval]) or irate(prometheus_tsdb_head_chunks_removed_total[5m])",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Reload block data from disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_tsdb_reloads_total[$interval]) - rate(prometheus_tsdb_reloads_failures_total[$interval])) or (irate(prometheus_tsdb_reloads_total[5m]) - irate(prometheus_tsdb_reloads_failures_total[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total[$interval]) or irate(prometheus_tsdb_reloads_failures_total[5m])",
       "legendFormat": "failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Scrapes Performed"
      },
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[$interval]) or irate(prometheus_tsdb_head_samples_appended_total[5m])",
       "legendFormat": "Samples appended in the head block"
      }
     ]
    },
    {
     "title": "Prometheus Targets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "count(up)", "legendFormat": "Targets Configured" },
      {
       "expr": "sum(avg_over_time(up[$interval])) or  sum(avg_over_time(up[5m]))",
       "legendFormat": "Avg Succesfully Scraped Targets"
      },
      {
       "expr": "sum(min_over_time(up[$interval])) or  sum(min_over_time(up[5m]))",
       "legendFormat": "Min Successfully Scraped Targets"
      }
     ]
    },
    {
     "title": "Scraped Target by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up[$interval])) by (job) or sum(avg_over_time(up[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds[$interval])) by (job) or avg(avg_over_time(scrape_duration_seconds[5m])) by (job) ",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scraped Target by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up[$interval])) by (instance) or sum(avg_over_time(up[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds[$interval])) by (instance) or avg(avg_over_time(scrape_duration_seconds[5m])) by (instance) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrapes by Target Frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[$interval]) or irate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "Rate of {{interval}} scrapes"
      }
     ]
    },
    {
     "title": "Scrape Frequency Versus Target",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_target_interval_length_seconds_sum[$interval]) / rate(prometheus_target_interval_length_seconds_count[$interval])) or (irate(prometheus_target_interval_length_seconds_sum[5m]) / irate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Actual  {{interval}} scrape interval  length"
      }
     ]
    },
    {
     "title": "Scraping Time Drift",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "time() - node_time", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Prometheus Scrape Interval Variance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/1",
       "legendFormat": "1sec  Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"5s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"5s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/5",
       "legendFormat": "5sec Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/60",
       "legendFormat": "1min Target Interval Variance"
      }
     ]
    },
    {
     "title": "Slowest Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_duration_seconds[$interval]) or max_over_time(scrape_duration_seconds[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    },
    {
     "title": "Largest Samples Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_samples_scraped[$interval]) or max_over_time(scrape_duration_seconds[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(prometheus_engine_queries[$interval]) or avg_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Avg Queries Active"
      },
      {
       "expr": "max_over_time(prometheus_engine_queries[$interval]) or max_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Max Queries Active"
      },
      {
       "expr": "prometheus_engine_queries_concurrent_max",
       "legendFormat": "Maximum Queries Permitted"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count[$interval]) or irate(prometheus_engine_query_duration_seconds_count[$interval]) ",
       "legendFormat": "{{slice}} - Executed"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_engine_query_duration_seconds_sum[$interval])/rate(prometheus_engine_query_duration_seconds_count[$interval])) or (irate(prometheus_engine_query_duration_seconds_sum[$interval])/irate(prometheus_engine_query_duration_seconds_count[$interval]))",
       "legendFormat": "{{slice}} - Avg Time"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[$interval])",
       "legendFormat": "{{slice}} - Load"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests duration by Handler",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[$interval]) or irate(prometheus_http_request_duration_seconds_sum[$interval])\n",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP Response Average Size by Handler",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_response_size_bytes_sum[$interval]) or\nirate(prometheus_http_response_size_bytes_sum[5m])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 metrics by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Top 10 hosts by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "clamp_max(sum by () ((rate(node_cpu{instance=\"pmm-server\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) or (irate(node_cpu{instance=\"pmm-server\",mode!=\"idle\",mode!=\"iowait\"}[5m]))) / count(node_cpu{mode=\"user\",instance=~\"pmm-server\"}),1) *100"
      }
     ]
    },
    {
     "title": "Mem Avail",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(node_memory_MemAvailable{instance=\"pmm-server\"} or (node_memory_MemFree{instance=\"pmm-server\"} + node_memory_Buffers{instance=\"pmm-server\"} + node_memory_Cached{instance=\"pmm-server\"})) / node_memory_MemTotal{instance=\"pmm-server\"} * 100"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_vmstat_pgpgin{instance=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"pmm-server\"}[5m]) * 1024"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_vmstat_pgpgout{instance=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"pmm-server\"}[5m]) * 1024"
      }
     ]
    },
    {
     "title": "Network IO",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(node_network_receive_bytes{instance=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes{instance=\"pmm-server\", device!=\"lo\"}[5m]))) + (sum(rate(node_network_transmit_bytes{instance=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes{instance=\"pmm-server\", device!=\"lo\"}[5m])))"
      }
     ]
    },
    {
     "title": "Sys Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "node_time{instance=\"pmm-server\"} - node_boot_time{instance=\"pmm-server\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PMM Server Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
     "content": "To simplify problem detection, you can download <a href=\"/managed/logs.zip\">server logs</a>. Please include this file if you are submitting a bug report   "
    }
   ]
  }
 ]
}