{
 "title": "Summary Dashboard",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "**CPU Usage**\n\nThe CPU Usage graph shows how much of the overall CPU time is used by the server.  It has 4 components: system, user, iowait and softirq.  System is the proportion of time the CPU spent inside the Linux kernel for operations like context switching, memory allocation and queue handling.  User is the time spent in the user space.  Normally, most of the MySQL CPU time is in user space, a too high value may indicate an indexing issue.  Iowait is the time the CPU spent waiting for disk IO requests to complete.  A high value of iowait indicates a disk bound load.  Softirq is the portion of time the CPU spent servicing software interrupts generated by the device drivers.  A high value of softirq may indicates a poorly configured device.  The network is generally the main source of high softirq values.   Be aware the graph presents global values, while there may be a lot of unused CPU, a single core may be saturated.  Look for any quantity saturating at 100/(cpu core count).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processes",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=\"$host\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=\"$host\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "**Network Traffic**\n\nThe Network Traffic graph shows the rate of data transferred over the network.  Outbound is the data sent by the server while Inbound is the data received by the server.  Look for signs of saturation given the capacity of the network devices.  If the outbound rate is constantly high and close to saturation and you have plenty of available CPU, you should consider activating the compression option on the MySQL clients and slaves.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "I/O Activity",
   "type": "graph",
   "description": "**I/O Activity**\n\nThe I/O Activity graph shows the rates of data read from (Page In) and written to (Page Out) the all the disks as collected from the vmstat bi and bo columns.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "**Disk Latency**\n\nThe Disk Latency graph shows the average time to complete read an write operations to the disks.  There is one data series per operation type (Read or Write) per disk mounted to the server.  High latency values, typically more than 15 ms,  are an indication of a disk bound workload saturating the storage subsystem or, a faulty/degraded hardware.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_ms{device!~\"dm-.+\", instance=\"$host\"}[$interval]) / rate(node_disk_reads_completed{device!~\"dm-.+\", instance=\"$host\"}[$interval])) or (irate(node_disk_read_time_ms{device!~\"dm-.+\", instance=\"$host\"}[5m]) / irate(node_disk_reads_completed{device!~\"dm-.+\", instance=\"$host\"}[5m])) or avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_ms{device!~\"dm-.+\", instance=\"$host\"}[$interval]) / rate(node_disk_writes_completed{device!~\"dm-.+\", instance=\"$host\"}[$interval])) or (irate(node_disk_write_time_ms{device!~\"dm-.+\", instance=\"$host\"}[5m]) / irate(node_disk_writes_completed{device!~\"dm-.+\", instance=\"$host\"}[5m])) or (avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[5m]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  { "title": "MySQL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MySQL Queries",
   "type": "graph",
   "description": "**MySQL Queries**\n\nThe MySQL Queries graph shows the rate of queries processed by MySQL.  The rate of queries is a rough indication of the MySQL server load.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThe InnoDB Row Operations graph shows the rate of rows processed by InnoDB.  It is a good indication of the MySQL server load.  A high value of Rows read, which can easily be above a million, is an indication of poor queries or deficient indexing.  The amounts of rows inserted, updated and deleted help appreciate the server write load.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[5m])",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  { "title": "Top MySQL Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Top MySQL Commands",
   "type": "graph",
   "description": "**Top MySQL Commands**\n\nThe Top MySQL Commands graph shows the rate of the various kind of SQL statements executed on the MySQL server.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  { "title": "Top MySQL Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top MySQL Handlers",
   "type": "graph",
   "description": "**Top MySQL Handlers**\n\nThe Top MySQL Handlers graph shows the rate of the various low level storage engine handler calls. The most important ones to watch are read_next and read_rnd_next.  A high values for read_rnd_next is an indication there are table scans while a high value of read_next is an indication of index scans.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_handlers_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_handlers_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}