{
 "title": "MongoDB Cluster Summary",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{bosh_job_name=~\"cfgsvr*|mongos\"}, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unsharded DBs",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_databases_total{type=\"unpartitioned\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded DBs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_databases_total{type=\"partitioned\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded Collections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_collections_total{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_shards_total{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_chunks_total{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_balancer_enabled{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Chunks Balanced",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_sharding_chunks_is_balanced{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Mongos Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg((rate(mongodb_mongod_op_counters_total{type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{type!=\"command\"}[5m])) * on (instance)  group_left \n label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongos  Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_connections{state=\"current\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Mongos  Cursors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongos_metrics_cursor_open{state=\"total\"} or mongodb_mongos_cursors{state=\"total_open\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Chunk Split Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{event=\"split\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{event=\"multi-split\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Change Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{ event=~\"addShard\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{ event=~\"removeShard.start\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{ event=~\"shardCollection\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{ event=~\"shardCollection.end\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "max(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(event) label_replace(increase(mongodb_mongos_sharding_changelog_10min_total{ event=~\"shardCollection.start\"}[$interval]),\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\"))by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_mongod_op_counters_total{type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{type!=\"command\"}[5m])) by (instance) * on (instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")) * on (instance) group_left(set) (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\"))) / (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")))) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Chunks by Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(mongodb_mongod_replset_my_state * on (instance) group_left(shard) max by (shard,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")),\"shard\",\"$1\",\"set\",\"(.*)\"))by (shard)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Connections Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connections{state=\"current\"} * on (instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")) * on (instance) group_left(set) (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")))/(mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\"))))by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Cursors Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{state=\"total\"} or mongodb_mongod_cursors{state=\"total_open\"}) by (instance) * on (instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")) * on (instance) group_left(set) (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\"))) / (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")))) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Replication Lag by Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\"} * on (instance) group_right(set) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\"))) by (set) - min(min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"}) by (instance,set) * on (instance) group_right(set) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\"))) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Oplog Range by Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp-mongodb_mongod_replset_oplog_tail_timestamp) by (instance) * on (instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")) * on (instance) group_left(set) (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\"))) / (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")))) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Shard Elections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max(changes(mongodb_mongod_replset_member_election_date[$interval]))by (instance,set) * on (instance) group_right(set) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")))by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Collection Lock Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_locks_time_locked_global_microseconds_total{database=\"Collection\"}) by (instance) * on (instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(.*)\")) * on (instance) group_left(set) (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\"))) / (mongodb_mongod_replset_my_state * on (instance) group_right(set) max by (set,instance) (label_replace(bosh_job_healthy{bosh_deployment=\"$deployment\"},\"instance\",\"$1:9001\",\"bosh_job_ip\",\"(^.*)\")))) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}