{
 "title": "MongoDB MMAPv1",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "query_result(bosh_job_healthy{bosh_job_name=~\"mongod|shard.*|cfgsvr\"} * on (bosh_job_ip) group_left(engine) max by (engine,bosh_job_ip) (label_replace(mongodb_mongod_storage_engine{engine=\"mmapv1\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))"
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": "query_result(sort(bosh_job_healthy{bosh_deployment=\"$deployment\"}) * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongod_replset_my_state{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(sort_desc(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(engine,set) max by (engine,set,bosh_job_ip) (label_replace(mongodb_mongod_storage_engine{engine=\"mmapv1\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\") * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongod_replset_my_state{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))))"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_replset_my_state{set=\"$replset\",instance=~\"$instance:.*\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lock Wait Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(increase(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=\"Database\"}[$interval])) by (instance) / (increase(mongodb_mongod_instance_uptime_seconds{instance=\"$host\"}[$interval])*1000000)) or mongodb_mongod_global_lock_ratio{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Write Lock Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=\"Global\",type=\"write\"}[$interval]) or irate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=\"Global\",type=\"write\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance:9100\"}"
    }
   ]
  },
  {
   "title": "Document Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    }
   ]
  },
  {
   "title": "Lock Ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=\"Database\"}[$interval])) by (instance) / (increase(mongodb_mongod_instance_uptime_seconds{instance=\"$host\"}[$interval])*1000000)) or mongodb_mongod_global_lock_ratio{instance=\"$host\"}",
     "legendFormat": "Lock Wait"
    }
   ]
  },
  {
   "title": "Lock Wait Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=~\"(Global|Database|MMAPV1Journal)\"}[$interval]) or irate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{instance=\"$host\",database=~\"(Global|Database|MMAPV1Journal)\"}[5m])",
     "legendFormat": "{{database}} {{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total{instance=\"$host\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{instance=\"$host\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "Journal Write Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_journaled_megabytes{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_durability_journaled_megabytes{instance=\"$host\"}[5m])",
     "legendFormat": "Journaled"
    },
    {
     "expr": "rate(mongodb_mongod_durability_write_to_data_files_megabytes{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_durability_write_to_data_files_megabytes{instance=\"$host\"}[5m])",
     "legendFormat": "Write to Data Files"
    }
   ]
  },
  {
   "title": "Journal Commit Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_commits{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_durability_commits{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Journaling Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_time_milliseconds_sum{instance=\"$host\",stage!=\"dt\"}[$interval]) or irate(mongodb_mongod_durability_time_milliseconds_sum{instance=\"$host\",stage!=\"dt\"}[5m])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Journaling Time - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_durability_time_milliseconds{instance=\"$host\",quantile=\"0.99\",stage!=\"dt\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Background Flushing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_background_flushing_average_milliseconds{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_background_flushing_average_milliseconds{instance=\"$host\"}[5m])",
     "legendFormat": "Background Flushing"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Client Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{instance=\"$host\", type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{instance=\"$host\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:.*\"}-node_memory_Mapped_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "Unmapped"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "Swap Cached"
    }
   ]
  },
  {
   "title": "Memory Dirty Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_nr_dirty{instance=\"$host\"}",
     "legendFormat": "Total Dirty Pages"
    },
    {
     "expr": "node_vmstat_nr_dirty_background_threshold{instance=\"$host\"}",
     "legendFormat": "Soft Dirty Page Threshold"
    },
    {
     "expr": "node_vmstat_nr_dirty_threshold{instance=\"$host\"}",
     "legendFormat": "Hard Dirty Page Threshold"
    }
   ]
  }
 ]
}