{
 "title": "MongoDB WiredTiger",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "query_result(bosh_job_healthy{bosh_job_name=~\"mongod|shard.*|cfgsvr\"} * on (bosh_job_ip) group_left(engine) max by (engine,bosh_job_ip) (label_replace(mongodb_mongod_storage_engine{engine=\"wiredTiger\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))"
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": "query_result(sort(bosh_job_healthy{bosh_deployment=\"$deployment\"}) * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongod_replset_my_state{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(sort_desc(bosh_job_healthy{bosh_deployment=~\"$deployment\"} * on (bosh_job_ip) group_left(engine,set) max by (engine,set,bosh_job_ip) (label_replace(mongodb_mongod_storage_engine{engine=\"wiredTiger\"},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\") * on (bosh_job_ip) group_left(set) max by (set,bosh_job_ip) (label_replace(mongodb_mongod_replset_my_state{},\"bosh_job_ip\",\"$1\",\"instance\",\"(^.*):.*\")))))"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_replset_my_state{set=\"$replset\",instance=~\"$instance:.*\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}/ ignoring(type) mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Cache Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"read\"}[5m])",
     "legendFormat": "Read into"
    },
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"written\"}[5m])",
     "legendFormat": "Written from"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{instance=\"$host\"}",
     "legendFormat": "Cursors"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_sessions_total{instance=\"$host\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Block Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Concurrency Tickets Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{instance=\"$host\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[5m])",
     "legendFormat": "current"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Log Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "Log Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  }
 ]
}