{
 "title": "RabbitMQ: Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_job_name=~\"rmq\"}, bosh_deployment)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(bosh_job_healthy{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=\"rmq\"}, bosh_job_ip)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(rabbitmq_up{instance=~\"$node:.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(rabbitmq_up{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rabbitmq_connectionsTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rabbitmq_consumersTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rabbitmq_channelsTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rabbitmq_queuesTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rabbitmq_exchangesTotal{instance=~\"$host\"})"
    }
   ]
  }
 ]
}